Dapperize

diff --git a/scripts/validate b/scripts/validate
--- a/scripts/validate
+++ b/scripts/validate
@@ -1,30 +1,20 @@
 #!/bin/bash
+set -e
 
 cd $(dirname $0)/..
 
-if [ -f ./build/bootstrap.envs ];then
-    . ./build/bootstrap.envs
-fi
+echo Running validation
 
-. ./scripts/common_functions
+PACKAGES=". $(find -name '*.go' | xargs -I{} dirname {} |  cut -f2 -d/ | sort -u | grep -Ev '(^\.$|.git|.trash-cache|vendor|bin)' | sed -e 's!^!./!' -e 's!$!/...!')"
 
-set_project_vars
-
-if [ -L ${PACKAGE} ]; then
-    rm ${PACKAGE}
-fi
-
-if [ ! -e ${PACKAGE} ]; then
-    mkdir -p $(dirname $PACKAGE)
-    ln -s $(pwd) $PACKAGE
-fi
-
-echo export GOPATH=$GOPATH
-export PATH=/go/bin:$PATH
-
-./scripts/gen-schema.sh
-if [ -n "$(git status --porcelain --untracked-files=no | grep -v generator/schemas.json)" ]; then
-    echo Modified files
-    git status --porcelain --untracked-files=no
-    exit 1
-fi
+echo Running: go vet
+go vet ${PACKAGES}
+#echo Running: golint
+#for i in ${PACKAGES}; do
+#    if [ -n "$(golint $i | grep -v 'should have comment.*or be unexported' | tee /dev/stderr)" ]; then
+#        failed=true
+#    fi
+#done
+#test -z "$failed"
+echo Running: go fmt
+test -z "$(go fmt ${PACKAGES} | tee /dev/stderr)"
